//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManagementEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long User_id { get; set; }
        public string User_name { get; set; }
        public string password { get; set; }
        public Nullable<long> customer_id { get; set; }
        public bool status { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string Role { get; set; }
        public Nullable<long> Updated_by { get; set; }
        public Nullable<long> Admin_id { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
